import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Layout
import Layout from "@/components/layout/Layout";

// Toast Container
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen w-full flex overflow-hidden`}
      >
        <Toaster />
        <Layout children={children} />
      </body>
    </html>
  );
}
